# Generated by Django 5.2.12 on 2026-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='estimated_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='health_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_high_protein',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_low_calorie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='nutrition_notes',
            field=models.TextField(blank=True),
        ),
    ]
