# Generated by Django 5.2.12 on 2026-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dish_estimated_calories_dish_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_keto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_slot',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=20),
        ),
    ]
