# Generated by Django 5.2.12 on 2026-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dish_is_keto_dish_meal_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='main_ingredient_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
