# Generated by Django 5.2.12 on 2026-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef', 'HomeChef'), ('resident', 'Resident'), ('rider', 'Rider')], max_length=20),
        ),
    ]
