# Generated by Django 5.2.12 on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_vehicle_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="society_name",
            new_name="location_name",
        ),
    ]
